{
    "Filter": [{
        "ID": "WebScrollerTest",
        "Caption": "WebScrollerTest",
        "QueryID": "ESTMTask\\WebScrollerTest\\WebScrollerTest_Q1.esq",
        "RootTable": "ESTMOpportunity",
        "SelectedMasterTable": "ESTMOpportunity",
        "SelectedMasterField": "",
        "TotalRow": "0",
        "ColumnHeaders": "0",
        "ColumnSetHeaders": "0",
        "ColumnSetRowCount": "2",
        "ColumnSetHeaderLines": "1",
        "HeaderLines": "1",
        "GroupByBoxVisible": "false",
        "FilterLineVisible": "false",
        "PreviewRow": "false",
        "PreviewRowMember": "",
        "PreviewRowLines": "3"
    }],
    "Param": [{
        "ID": "Code",
        "AA": "1",
        "Caption": "Κωδικός",
        "Tooltip": "Κωδικός",
        "ControlType": "0",
        "ParameterType": "System.String, mscorlib",
        "Precision": "0",
        "MultiValued": "true",
        "Visible": "true",
        "Required": "false",
        "ODSTag": "9BBC9CFF-6458-4F74-BB9B-016E13E24084",
        "InvQueryID": "ESTMTask\\WebScrollerTest\\WebScrollerTest_Q2.esq",
        "InvSelectedMasterTable": "ESTMTask",
        "InvSelectedMasterField": "Code",
        "InvTableMappings": "ESTMTask",
        "Tags": "",
        "Visibility": "0"
    }, {
        "ID": "ESDCreated",
        "AA": "2",
        "Caption": "Ημ/νία δημιουργίας",
        "Tooltip": "Ημ/νία δημιουργίας",
        "ControlType": "6",
        "ParameterType": "Entersoft.Framework.Platform.ESDateRange, QueryProcess",
        "Precision": "0",
        "MultiValued": "false",
        "Visible": "true",
        "Required": "false",
        "ODSTag": "252F10D5-C34B-4943-844D-2E1EF108FEB2",
        "Tags": "",
        "Visibility": "0"
    }, {
        "ID": "OppRevenue",
        "AA": "3",
        "Caption": "Έσοδα ευκαιρίας",
        "Tooltip": "Έσοδα ευκαιρίας",
        "ControlType": "8",
        "ParameterType": "Entersoft.Framework.Platform.ESNumeric, QueryProcess",
        "Precision": "5",
        "MultiValued": "false",
        "Visible": "true",
        "Required": "false",
        "ODSTag": "1A3CCE88-5A60-436F-B7D2-11B8F18FB5FB",
        "Tags": "",
        "Visibility": "0"
    }],
    "DefaultValue": [{
        "fParamID": "ESDCreated",
        "Value": "ESDateRange(Year)"
    }, {
        "fParamID": "OppRevenue",
        "Value": "ESNumeric(GE, '0')"
    }],
    "LayoutColumn": [{
        "fFilterID": "WebScrollerTest",
        "ColName": "Code",
        "AA": "0",
        "Caption": "Κωδικός",
        "FormatString": "",
        "Width": "377",
        "ODSTag": "9BBC9CFF-6458-4F74-BB9B-016E13E24084",
        "Visible": "true",
        "ColumnSetRow": "-1",
        "ColumnSetColumn": "-1",
        "RowSpan": "-1",
        "ColSpan": "-1",
        "AggregateFunction": "0",
        "TextAlignment": "1",
        "EditType": "1",
        "DataTypeName": "String"
    }, {
        "fFilterID": "WebScrollerTest",
        "ColName": "OppRevenue",
        "AA": "1",
        "Caption": "Έσοδα ευκαιρίας",
        "FormatString": "#,0.00",
        "Width": "762",
        "ODSTag": "1A3CCE88-5A60-436F-B7D2-11B8F18FB5FB",
        "Visible": "true",
        "ColumnSetRow": "-1",
        "ColumnSetColumn": "-1",
        "RowSpan": "-1",
        "ColSpan": "-1",
        "AggregateFunction": "2",
        "TextAlignment": "3",
        "EditType": "1",
        "DataTypeName": "Decimal"
    }, {
        "fFilterID": "WebScrollerTest",
        "ColName": "ESDCreated",
        "AA": "2",
        "Caption": "Ημ/νία δημιουργίας",
        "FormatString": "d",
        "Width": "694",
        "ODSTag": "252F10D5-C34B-4943-844D-2E1EF108FEB2",
        "Visible": "true",
        "ColumnSetRow": "-1",
        "ColumnSetColumn": "-1",
        "RowSpan": "-1",
        "ColSpan": "-1",
        "AggregateFunction": "0",
        "TextAlignment": "1",
        "EditType": "0",
        "DataTypeName": "DateTime"
    }],
    "FormatingCondition": [{
        "fFilterID": "WebScrollerTest",
        "Key": "OppRevenueMarkNegativeValues",
        "AllowMerge": "true",
        "ColumnKey": "OppRevenue",
        "ConditionOperator": "3",
        "Value1": "0",
        "TargetColumnKey": "OppRevenue",
        "fFormatStyleKey": "930161da-5040-4bab-b5f5-e3254a8c375f"
    }],
    "FormatStyle": [{
        "Key": "930161da-5040-4bab-b5f5-e3254a8c375f",
        "BackColor": "0",
        "ForeColor": "-65536",
        "FontBold": "0",
        "FontItalic": "0",
        "FontStrikeout": "0"
    }]
}
